#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGGameEventModel.h"


@protocol SWGGameModel
@end

@interface SWGGameModel : SWGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSArray<SWGGameEventModel>* events;

@end
