#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGGameEventModel.h"


@protocol SWGGameFooEventModel
@end

@interface SWGGameFooEventModel : SWGGameEventModel


@property(nonatomic) NSString* gameEventModelType;

@property(nonatomic) NSString* name;

@end
