#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPoint
@end

@interface SWGPoint : SWGObject


@property(nonatomic) NSNumber* x;

@property(nonatomic) NSNumber* y;

@end
